name: package
on: [push, pull_request]

jobs:
  build_package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get-hash
      id: hash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: run-build
      run: python3 build_package.py --set-version ${{ steps.vars.outputs.sha_short }}
    - name: artifact package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: dist/weewx-json_${{ steps.vars.outputs.sha_short }}.tar.gz
