name: package
on: [push, pull_request]

jobs:
  build_package:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: get-hash
      id: hash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"     
    - name: run-build
      run: python3 build_package.py --set-version ${{ steps.hash.outputs.sha_short }}
    - name: artifact package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: dist/weewx-json_${{ steps.hash.outputs.sha_short }}.tar.gz
